POST http://localhost:5000/api/addusers HTTP/1.1
content-type: application/json

{
    "first_name": "Srikanth",
    "last_name": "D",
    "email": "SrikanthD@gmail.com",
    "password": "#10Rossi",
    "country": "India",
    "country_code": "+91",
    "phone_number": "7663842862",
    "dob": "1994-12-21",
    "is_org": true,
    "org_name": "ANZ"
}